openapi: "3.0.0"
info:
  version: 0.0.1
  title: post-services
  description: Api servicios de post
  termsOfService: http://swagger.io/terms/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:3000/posts/v1
  - url: http://test.com/posts/v1
  - url: http://production.com/posts/v1
paths:
  /getPosts/{limit}/{page}:
    get:
      description: Retorna los Post paginados
      operationId: getPosts
      parameters:
        - name: limit
          in: path
          description: cantidad limite para paginar
          required: true
          schema:
            type: integer
            format: int64
        - name: page
          in: path
          description: numero de la paginacion
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: get client response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /createPost:
    post:
      description: Registra un post nuevo
      operationId: createPost
      requestBody:
        description: Campos requeridos
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreatePost"
      responses:
        "200":
          description: login response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /updatePost:
    patch:
      description: Actualiza el estado un cliente
      operationId: updatePost
      requestBody:
        description: Campos requeridos
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdatePost"
      responses:
        "200":
          description: login response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    CreatePost:
      required:
        - name
        - content
        - user_email
      properties:
        name:
          type: string
        content:
          type: number
        identification_number:
          type: string
        user_email:
          type: number        
    UpdatePost:
      required:
        - id_post
        - new_message
      properties:
        id_post:
          type: number
        new_message:
          type: string
    Response:
      required:
        - response
        - error
      properties:
        response:
          type: object
        error:
          type: number
    Error:
      required:
        - message
        - error
      properties:
        message:
          type: string
        error:
          type: boolean

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
